In [1]:
#Question 3.1
import pandas as pd
import numpy as np

In [2]:
#Question 3.2
pokemon = pd.read_csv("/Users/kieranmcavoy/Documents/Data Science/Big Data Technologies/Lab 2/pokemon_alopez247.csv")

In [3]:
#Question 3.3
pokemon.isnull()

,Number,Name,Type_1,Type_2,Total,HP,Attack,Defense,Sp_Atk,Sp_Def,...,Color,hasGender,Pr_Male,Egg_Group_1,Egg_Group_2,hasMegaEvolution,Height_m,Weight_kg,Catch_Rate,Body_Style
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
716,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,True,False,False,False,False,False
717,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,True,False,False,False,False,False
718,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,True,False,False,False,False,False
719,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,True,False,False,False,False,False
720,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,True,False,False,False,False,False

In [4]:
pokemon.notnull()

,Number,Name,Type_1,Type_2,Total,HP,Attack,Defense,Sp_Atk,Sp_Def,...,Color,hasGender,Pr_Male,Egg_Group_1,Egg_Group_2,hasMegaEvolution,Height_m,Weight_kg,Catch_Rate,Body_Style
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,False,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,False,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
716,True,True,True,True,True,True,True,True,True,True,...,True,True,False,True,False,True,True,True,True,True
717,True,True,True,True,True,True,True,True,True,True,...,True,True,False,True,False,True,True,True,True,True
718,True,True,True,True,True,True,True,True,True,True,...,True,True,False,True,False,True,True,True,True,True
719,True,True,True,True,True,True,True,True,True,True,...,True,True,False,True,False,True,True,True,True,True
720,True,True,True,True,True,True,True,True,True,True,...,True,True,False,True,False,True,True,True,True,True

In [6]:
#Question3.4
pokemon.drop(columns = ["Type_2","Egg_Group_2"])

,Number,Name,Type_1,Total,HP,Attack,Defense,Sp_Atk,Sp_Def,Speed,...,isLegendary,Color,hasGender,Pr_Male,Egg_Group_1,hasMegaEvolution,Height_m,Weight_kg,Catch_Rate,Body_Style
0,1,Bulbasaur,Grass,318,45,49,49,65,65,45,...,False,Green,True,0.875,Monster,False,0.71,6.9,45,quadruped
1,2,Ivysaur,Grass,405,60,62,63,80,80,60,...,False,Green,True,0.875,Monster,False,0.99,13.0,45,quadruped
2,3,Venusaur,Grass,525,80,82,83,100,100,80,...,False,Green,True,0.875,Monster,True,2.01,100.0,45,quadruped
3,4,Charmander,Fire,309,39,52,43,60,50,65,...,False,Red,True,0.875,Monster,False,0.61,8.5,45,bipedal_tailed
4,5,Charmeleon,Fire,405,58,64,58,80,65,80,...,False,Red,True,0.875,Monster,False,1.09,19.0,45,bipedal_tailed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
716,717,Yveltal,Dark,680,126,131,95,131,98,99,...,True,Red,False,NaN,Undiscovered,False,5.79,203.0,45,two_wings
717,718,Zygarde,Dragon,600,108,100,121,81,95,95,...,True,Green,False,NaN,Undiscovered,False,5.00,305.0,3,serpentine_body
718,719,Diancie,Rock,600,50,100,150,100,150,50,...,True,Pink,False,NaN,Undiscovered,True,0.71,8.8,3,head_arms
719,720,Hoopa,Psychic,600,80,110,60,150,130,70,...,True,Purple,False,NaN,Undiscovered,False,0.51,9.0,3,head_only
720,721,Volcanion,Fire,600,80,110,120,130,90,70,...,True,Brown,False,NaN,Undiscovered,False,1.70,195.0,3,quadruped

In [7]:
#Question 3.5
pokemon.dropna()

,Number,Name,Type_1,Type_2,Total,HP,Attack,Defense,Sp_Atk,Sp_Def,...,Color,hasGender,Pr_Male,Egg_Group_1,Egg_Group_2,hasMegaEvolution,Height_m,Weight_kg,Catch_Rate,Body_Style
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,...,Green,True,0.875,Monster,Grass,False,0.71,6.9,45,quadruped
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,...,Green,True,0.875,Monster,Grass,False,0.99,13.0,45,quadruped
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,...,Green,True,0.875,Monster,Grass,True,2.01,100.0,45,quadruped
5,6,Charizard,Fire,Flying,534,78,84,78,109,85,...,Red,True,0.875,Monster,Dragon,True,1.70,90.5,45,bipedal_tailed
33,34,Nidoking,Poison,Ground,505,81,102,77,85,75,...,Purple,True,1.000,Monster,Field,False,1.40,62.0,45,bipedal_tailed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,696,Tyrunt,Rock,Dragon,362,58,89,77,45,45,...,Brown,True,0.875,Monster,Dragon,False,0.79,26.0,45,bipedal_tailed
696,697,Tyrantrum,Rock,Dragon,521,82,121,119,69,59,...,Red,True,0.875,Monster,Dragon,False,2.49,270.0,45,bipedal_tailed
701,702,Dedenne,Electric,Fairy,431,67,58,57,81,67,...,Yellow,True,0.500,Field,Fairy,False,0.20,2.2,180,bipedal_tailed
707,708,Phantump,Ghost,Grass,309,43,70,48,50,60,...,Brown,True,0.500,Grass,Amorphous,False,0.41,7.0,120,head_arms
708,709,Trevenant,Ghost,Grass,474,85,110,76,65,82,...,Brown,True,0.500,Grass,Amorphous,False,1.50,71.0,60,several_limbs

In [17]:
#Question3.6
for column in pokemon.columns:
    mode_value = pokemon[column].mode().iloc[0]  # Calculate the mode for the column
    pokemon[column].fillna(mode_value, inplace=True)

    
print(pokemon)

     Number        Name   Type_1  Type_2  Total   HP  Attack  Defense  Sp_Atk  \
0         1   Bulbasaur    Grass  Poison    318   45      49       49      65
1         2     Ivysaur    Grass  Poison    405   60      62       63      80
2         3    Venusaur    Grass  Poison    525   80      82       83     100
3         4  Charmander     Fire  Flying    309   39      52       43      60
4         5  Charmeleon     Fire  Flying    405   58      64       58      80
..      ...         ...      ...     ...    ...  ...     ...      ...     ...
716     717     Yveltal     Dark  Flying    680  126     131       95     131
717     718     Zygarde   Dragon  Ground    600  108     100      121      81
718     719     Diancie     Rock   Fairy    600   50     100      150     100
719     720       Hoopa  Psychic   Ghost    600   80     110       60     150
720     721   Volcanion     Fire   Water    600   80     110      120     130

     Sp_Def  ...   Color  hasGender  Pr_Male   Egg_Group_1  Egg_Group_2  \
0        65  ...   Green       True    0.875       Monster        Grass
1        80  ...   Green       True    0.875       Monster        Grass
2       100  ...   Green       True    0.875       Monster        Grass
3        50  ...     Red       True    0.875       Monster       Dragon
4        65  ...     Red       True    0.875       Monster       Dragon
..      ...  ...     ...        ...      ...           ...          ...
716      98  ...     Red      False    0.500  Undiscovered       Dragon
717      95  ...   Green      False    0.500  Undiscovered       Dragon
718     150  ...    Pink      False    0.500  Undiscovered       Dragon
719     130  ...  Purple      False    0.500  Undiscovered       Dragon
720      90  ...   Brown      False    0.500  Undiscovered       Dragon

     hasMegaEvolution Height_m Weight_kg  Catch_Rate       Body_Style
0               False     0.71       6.9          45        quadruped
1               False     0.99      13.0          45        quadruped
2                True     2.01     100.0          45        quadruped
3               False     0.61       8.5          45   bipedal_tailed
4               False     1.09      19.0          45   bipedal_tailed
..                ...      ...       ...         ...              ...
716             False     5.79     203.0          45        two_wings
717             False     5.00     305.0           3  serpentine_body
718              True     0.71       8.8           3        head_arms
719             False     0.51       9.0           3        head_only
720             False     1.70     195.0           3        quadruped

[721 rows x 23 columns]